name: boop-friday
version: 0.0.1
summary: Just a test python snap
description: >
  Just a test python snap

confinement: devmode
base: core18

parts:
  boop-friday:
    plugin: python
    python-version: python3
    source: .

apps:
  boop-friday:
    command: python3 pythonFile.py