name: boop-friday
version: 1.5.0
summary: A better longer summary goes here
description: >
    Winter kept us warm, covering
    Earth in forgetful snow, feeding
    A little life with dried tubers.
    Summer surprised us, coming over the Starnbergersee
    With a shower of rain; we stopped in the colonnade,
    And went on in sunlight, into the Hofgarten,
    And drank coffee, and talked for an hour.
    Bin gar keine Russin, stamm’ aus Litauen, echt deutsch.
    And when we were children, staying at the arch-duke’s,
    My cousin’s, he took me out on a sled,
    And I was frightened. He said, Marie,
    Marie, hold on tight. And down we went.
    New thing here
    Another change. Now.

confinement: strict
grade: stable
base: core18

parts:
  boop-friday:
    plugin: python
    python-version: python3
    source: .

apps:
  boop-friday:
    command: python3 boop-friday.py
