name: boop-friday
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Well you have to start somewhere # 79 char long summary
  description: |
    Less than a hundred word summary is likely. But not certain.
  grade: devel # must be 'stable' to release into candidate/stable channels
  base: core18
  confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  boop-friday:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - python-six
apps:
  boop-friday:
    command: bin/boop-friday.py